"""
setup_utility.py  --  Albedo First-Run Setup Wizard

Self-contained deployment GUI. Runs before the albedo package is
installed, so nothing from albedo.* is imported at module level.

Pages:
  1  System Check  -- Python 3.12, Ollama, Git
  2  Directories   -- install root, RAG knowledge-base folders
  3  Installing    -- live pip output + progress bar
  4  Complete      -- launch shortcut / exit

Errno 13 fix: all pip commands use --no-cache-dir so no wheel file
in the pip cache directory is ever held open when another process
has already locked it.
"""
from __future__ import annotations

import os
import queue
import shutil
import subprocess
import sys
import threading
from pathlib import Path
from datetime import datetime
import tkinter as tk
from tkinter import filedialog

import customtkinter as ctk

# ── Theme ──────────────────────────────────────────────────────────────────
ctk.set_appearance_mode("Dark")
ctk.set_default_color_theme("blue")

C_BG      = "#0A0F2C"
C_PANEL   = "#0E1330"
C_CYAN    = "#00F5FF"
C_DIM     = "#0099BB"
C_BORDER  = "#1A2050"
C_TEXT    = "#C8D4E8"
C_MUTED   = "#3A4570"
C_GREEN   = "#00CC66"
C_WARN    = "#FFAA00"
C_DANGER  = "#FF3A5C"

ROOT = Path(__file__).parent
VENV = ROOT / ".venv"
VENV_PY  = VENV / "Scripts" / "python.exe"
VENV_PIP = VENV / "Scripts" / "pip.exe"


# ── Helpers ────────────────────────────────────────────────────────────────

def _run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, timeout=30, **kw)


def _find_python312() -> str | None:
    """Return the path to a Python 3.12.x executable, or None."""
    # Try the Python Launcher first (most reliable on Windows)
    try:
        r = _run(["py", "-3.12", "-c", "import sys; print(sys.executable)"])
        if r.returncode == 0:
            return r.stdout.strip()
    except FileNotFoundError:
        pass
    # Try explicit names
    for name in ("python3.12", "python"):
        exe = shutil.which(name)
        if exe:
            try:
                r = _run([exe, "-c",
                          "import sys; v=sys.version_info; "
                          "print(sys.executable if (v.major,v.minor)==(3,12) else '')"])
                if r.returncode == 0 and r.stdout.strip():
                    return r.stdout.strip()
            except Exception:
                pass
    return None


def _check_ollama() -> bool:
    try:
        r = _run(["ollama", "--version"])
        return r.returncode == 0
    except FileNotFoundError:
        return False


def _check_git() -> bool:
    try:
        r = _run(["git", "--version"])
        return r.returncode == 0
    except FileNotFoundError:
        return False


def _kill_locked_processes() -> None:
    """
    Kill pythonw.exe processes that may hold pip cache file locks.
    Avoids killing python.exe (would kill this process) or all Python.
    Only targets GUI (pythonw) instances -- those are the ones holding
    the Albedo Mission Control window open during an update.
    """
    for name in ("pythonw.exe",):
        try:
            subprocess.run(["taskkill", "/F", "/IM", name],
                           capture_output=True, timeout=5)
        except Exception:
            pass


def _write_env(chaotic: str, exotic: str, piper_bin: str,
               piper_voice: str, wakeword: str) -> None:
    env_path = ROOT / ".env"
    example  = ROOT / ".env.example"
    if example.exists():
        lines = example.read_text(encoding="utf-8").splitlines()
    else:
        lines = []
    overrides = {
        "CHAOTIC_3D_PATH": chaotic,
        "EXOTIC_OS_PATH":  exotic,
        "PIPER_BINARY":    piper_bin,
        "PIPER_VOICE_MODEL": piper_voice,
        "WAKEWORD_MODEL":  wakeword,
        "OLLAMA_MODEL":    "llama3.2:3b",
        "WHISPER_MODEL_SIZE": "small",
        "WHISPER_DEVICE":  "cuda",
        "WHISPER_COMPUTE_TYPE": "int8_float16",
    }
    result: list[str] = [
        f"# Generated by setup_utility.py -- {datetime.now():%Y-%m-%d %H:%M}",
        "",
    ]
    written: set[str] = set()
    for line in lines:
        k = line.split("=")[0].strip().lstrip("#").strip()
        if k in overrides:
            result.append(f'{k}="{overrides[k]}"')
            written.add(k)
        else:
            result.append(line)
    for k, v in overrides.items():
        if k not in written:
            result.append(f'{k}="{v}"')
    env_path.write_text("\n".join(result) + "\n", encoding="utf-8")


def _create_shortcut(install_root: Path) -> None:
    launcher = install_root / "Launch-Albedo.ps1"
    desktop  = Path(os.path.expandvars("%USERPROFILE%")) / "Desktop"
    lnk_path = desktop / "Albedo.lnk"
    ico_path = install_root / "albedo_icon.ico"

    if lnk_path.exists():
        lnk_path.unlink()

    try:
        import win32com.client  # type: ignore
        shell    = win32com.client.Dispatch("WScript.Shell")
        shortcut = shell.CreateShortcut(str(lnk_path))
        shortcut.TargetPath       = "powershell.exe"
        shortcut.Arguments        = (f'-ExecutionPolicy Bypass -WindowStyle Normal '
                                     f'-File "{launcher}"')
        shortcut.WorkingDirectory = str(install_root)
        shortcut.Description      = "Launch Albedo -- Spartan-Class Local AI"
        shortcut.IconLocation     = (f"{ico_path},0" if ico_path.exists()
                                     else "powershell.exe,0")
        shortcut.Save()
    except Exception:
        # win32com not available yet -- fall back to PowerShell
        try:
            ps = (
                f'$s=$([System.Runtime.InteropServices.RuntimeEnvironment]::'
                f'GetRuntimeDirectory()); '
                f'$ws=New-Object -ComObject WScript.Shell; '
                f'$lnk=$ws.CreateShortcut("{lnk_path}"); '
                f'$lnk.TargetPath="powershell.exe"; '
                f'$lnk.Arguments='
                f'"-ExecutionPolicy Bypass -WindowStyle Normal -File `"{launcher}`""; '
                f'$lnk.WorkingDirectory="{install_root}"; '
                f'$lnk.IconLocation="{ico_path},0"; '
                f'$lnk.Save()'
            )
            subprocess.run(["powershell", "-NoProfile", "-Command", ps],
                           capture_output=True, timeout=15)
        except Exception:
            pass


# ── UI helpers ─────────────────────────────────────────────────────────────

def _label(parent, text, size=12, color=C_TEXT, bold=False, **kw):
    font = ("Courier New", size, "bold" if bold else "normal")
    return ctk.CTkLabel(parent, text=text, font=font, text_color=color, **kw)


def _check_row(parent, label: str, ok: bool | None) -> ctk.CTkLabel:
    """Return the status label so callers can update it later."""
    row = ctk.CTkFrame(parent, fg_color="transparent")
    row.pack(fill="x", padx=24, pady=4)
    _label(row, f"  {label}", size=12).pack(side="left")
    if ok is None:
        status_text, color = "CHECKING...", C_MUTED
    elif ok:
        status_text, color = "OK", C_GREEN
    else:
        status_text, color = "MISSING", C_DANGER
    lbl = _label(row, status_text, color=color, size=12)
    lbl.pack(side="right", padx=8)
    return lbl


# ── Pages ──────────────────────────────────────────────────────────────────

class Page(ctk.CTkFrame):
    def __init__(self, parent, wizard: "SetupWizard"):
        super().__init__(parent, fg_color=C_BG)
        self.wizard = wizard

    def on_enter(self) -> None:
        pass


class SystemCheckPage(Page):
    def __init__(self, parent, wizard: "SetupWizard"):
        super().__init__(parent, wizard)
        self._results: dict[str, bool | None] = {
            "Python 3.12": None, "Ollama": None, "Git": None,
        }
        self._labels: dict[str, ctk.CTkLabel] = {}
        self._build()

    def _build(self) -> None:
        _label(self, "STEP 1  --  SYSTEM CHECK", size=14, bold=True,
               color=C_CYAN).pack(pady=(24, 4))
        _label(self, "Verifying required dependencies before installation.",
               color=C_MUTED).pack(pady=(0, 16))

        box = ctk.CTkFrame(self, fg_color=C_PANEL, corner_radius=8)
        box.pack(fill="x", padx=24, pady=8)

        for name in self._results:
            self._labels[name] = _check_row(box, name, None)

        self._fix_btn = ctk.CTkButton(
            self, text="FIX MISSING DEPENDENCIES", width=260,
            font=("Courier New", 12, "bold"),
            fg_color=C_WARN, hover_color="#CC8800", text_color="#000000",
            command=self._fix)
        self._fix_btn.pack(pady=12)
        self._fix_btn.configure(state="disabled")

        self._note = _label(self, "", color=C_MUTED, size=10)
        self._note.pack(pady=4)

    def on_enter(self) -> None:
        threading.Thread(target=self._run_checks, daemon=True).start()

    def _run_checks(self) -> None:
        checks = {
            "Python 3.12": _find_python312() is not None,
            "Ollama":       _check_ollama(),
            "Git":          _check_git(),
        }
        for name, ok in checks.items():
            self._results[name] = ok
            color = C_GREEN if ok else C_DANGER
            text  = "OK" if ok else "MISSING"
            self.after(0, lambda lbl=self._labels[name], t=text, c=color:
                       lbl.configure(text=t, text_color=c))

        all_ok = all(checks.values())
        any_missing = not all_ok
        self.after(0, lambda: self._fix_btn.configure(
            state="normal" if any_missing else "disabled"))
        self.after(0, lambda: self.wizard.set_next_enabled(all_ok))
        if all_ok:
            self.after(0, lambda: self._note.configure(
                text="All dependencies found. Click NEXT to continue.",
                text_color=C_GREEN))

    def _fix(self) -> None:
        self._fix_btn.configure(state="disabled", text="Installing...")
        self._note.configure(text="Installing missing tools via winget...",
                             text_color=C_WARN)

        def _run() -> None:
            if not self._results.get("Ollama"):
                try:
                    subprocess.run(
                        ["winget", "install", "Ollama.Ollama",
                         "--accept-source-agreements",
                         "--accept-package-agreements", "--silent"],
                        timeout=120)
                except Exception:
                    pass
            # Python 3.12 install if missing
            if not self._results.get("Python 3.12"):
                try:
                    subprocess.run(
                        ["winget", "install",
                         "Python.Python.3.12",
                         "--accept-source-agreements",
                         "--accept-package-agreements", "--silent"],
                        timeout=180)
                except Exception:
                    pass
            self.after(0, self.on_enter)
            self.after(0, lambda: self._fix_btn.configure(
                text="FIX MISSING DEPENDENCIES"))

        threading.Thread(target=_run, daemon=True).start()


class DirectoryPage(Page):
    def __init__(self, parent, wizard: "SetupWizard"):
        super().__init__(parent, wizard)
        self._build()

    def _build(self) -> None:
        _label(self, "STEP 2  --  DIRECTORY SELECTION", size=14, bold=True,
               color=C_CYAN).pack(pady=(24, 4))
        _label(self, "Choose your knowledge-base source folders.",
               color=C_MUTED).pack(pady=(0, 16))

        box = ctk.CTkFrame(self, fg_color=C_PANEL, corner_radius=8)
        box.pack(fill="x", padx=24, pady=8)

        self._3d_var   = ctk.StringVar(value="")
        self._os_var   = ctk.StringVar(value="")
        self._piper_var = ctk.StringVar(value=r"C:\piper\piper.exe")
        self._voice_var = ctk.StringVar(
            value=r"C:\piper\voices\en_US-kristin-medium.onnx")
        self._wake_var  = ctk.StringVar(value="hey_jarvis")

        self._dir_row(box, "Chaotic 3D Folder  (STL / gcode / slicer)",
                      self._3d_var)
        self._dir_row(box, "Exotic OS Folder   (Python / logs / reptile records)",
                      self._os_var)

        sep = ctk.CTkFrame(box, height=1, fg_color=C_BORDER)
        sep.pack(fill="x", padx=16, pady=8)

        self._path_row(box, "Piper binary path", self._piper_var)
        self._path_row(box, "Voice model (.onnx)", self._voice_var)
        self._path_row(box, "Wake word model",     self._wake_var)

        _label(self,
               "Leave 3D / OS folders blank to configure later via SETTINGS.",
               color=C_MUTED, size=10).pack(pady=(8, 0))

    def _dir_row(self, parent, label: str, var: ctk.StringVar) -> None:
        row = ctk.CTkFrame(parent, fg_color="transparent")
        row.pack(fill="x", padx=16, pady=4)
        _label(row, label, size=11).pack(anchor="w")
        inner = ctk.CTkFrame(row, fg_color="transparent")
        inner.pack(fill="x")
        ctk.CTkEntry(inner, textvariable=var, fg_color=C_BG,
                     border_color=C_BORDER, text_color=C_TEXT,
                     font=("Courier New", 11), height=34).pack(
            side="left", fill="x", expand=True, padx=(0, 4))
        ctk.CTkButton(inner, text="BROWSE", width=80, height=34,
                      font=("Courier New", 10), fg_color=C_BORDER,
                      hover_color=C_DIM,
                      command=lambda v=var: v.set(
                          filedialog.askdirectory() or v.get()
                      )).pack(side="left")

    def _path_row(self, parent, label: str, var: ctk.StringVar) -> None:
        row = ctk.CTkFrame(parent, fg_color="transparent")
        row.pack(fill="x", padx=16, pady=4)
        _label(row, label, size=11).pack(anchor="w")
        ctk.CTkEntry(row, textvariable=var, fg_color=C_BG,
                     border_color=C_BORDER, text_color=C_TEXT,
                     font=("Courier New", 11), height=34).pack(fill="x")

    def get_values(self) -> dict[str, str]:
        return {
            "chaotic":    self._3d_var.get().strip(),
            "exotic":     self._os_var.get().strip(),
            "piper_bin":  self._piper_var.get().strip(),
            "piper_voice": self._voice_var.get().strip(),
            "wakeword":   self._wake_var.get().strip(),
        }


class InstallPage(Page):
    def __init__(self, parent, wizard: "SetupWizard"):
        super().__init__(parent, wizard)
        self._q: queue.Queue = queue.Queue()
        self._build()

    def _build(self) -> None:
        _label(self, "STEP 3  --  INSTALLING", size=14, bold=True,
               color=C_CYAN).pack(pady=(24, 4))

        self._status = _label(self, "Ready.", color=C_MUTED)
        self._status.pack(pady=(0, 8))

        self._bar = ctk.CTkProgressBar(self, progress_color=C_CYAN,
                                       fg_color=C_BORDER, height=16)
        self._bar.pack(fill="x", padx=24, pady=(0, 12))
        self._bar.set(0)

        log_frame = ctk.CTkFrame(self, fg_color=C_PANEL, corner_radius=8)
        log_frame.pack(fill="both", expand=True, padx=24, pady=(0, 12))

        self._log = ctk.CTkTextbox(log_frame, font=("Courier New", 10),
                                   fg_color=C_PANEL, text_color=C_TEXT,
                                   wrap="word", state="disabled",
                                   border_width=0)
        self._log.pack(fill="both", expand=True, padx=4, pady=4)
        self._log._textbox.tag_config("ok",   foreground=C_GREEN)
        self._log._textbox.tag_config("err",  foreground=C_DANGER)
        self._log._textbox.tag_config("info", foreground=C_MUTED)

    def on_enter(self) -> None:
        dirs = self.wizard.dir_page.get_values()
        self.wizard.set_next_enabled(False)
        self._bar.set(0)
        threading.Thread(target=self._install, args=(dirs,), daemon=True).start()
        self.after(50, self._poll)

    def _poll(self) -> None:
        try:
            while True:
                msg, tag, pct = self._q.get_nowait()
                self._append(msg, tag)
                if pct is not None:
                    self._bar.set(pct)
                    self._status.configure(text=msg[:60])
        except queue.Empty:
            pass
        self.after(50, self._poll)

    def _push(self, msg: str, tag: str = "info", pct: float | None = None) -> None:
        self._q.put((msg, tag, pct))

    def _append(self, text: str, tag: str = "info") -> None:
        tb = self._log._textbox
        self._log.configure(state="normal")
        tb.insert("end", text.rstrip() + "\n", tag)
        self._log.configure(state="disabled")
        tb.see("end")

    # ── Installation sequence ──────────────────────────────────────────────

    def _install(self, dirs: dict[str, str]) -> None:
        try:
            self._step_kill_locked()
            py312 = self._step_venv()
            self._step_build_tools()
            self._step_requirements()
            self._step_playwright()
            self._step_wakeword_models()
            self._step_env(dirs)
            self._step_shortcut()
            self._step_ollama()
            self._push("", "info", 1.0)
            self._push("Installation complete!", "ok")
            self.after(0, lambda: self.wizard.go_to_complete(success=True))
        except Exception as exc:
            self._push(f"FATAL: {exc}", "err")
            self.after(0, lambda: self.wizard.go_to_complete(success=False))

    def _step_kill_locked(self) -> None:
        self._push("Closing any running Albedo windows...", "info", 0.02)
        _kill_locked_processes()

    def _step_venv(self) -> str:
        self._push("Locating Python 3.12...", "info", 0.05)
        py = _find_python312()
        if py is None:
            raise RuntimeError(
                "Python 3.12 not found. Install it via winget or python.org "
                "and re-run this wizard.")
        self._push(f"  Found: {py}", "ok")

        if VENV.exists():
            self._push("  Existing .venv detected -- reusing.", "info", 0.08)
        else:
            self._push("Creating virtual environment...", "info", 0.10)
            r = subprocess.run([py, "-m", "venv", str(VENV)],
                               capture_output=True, text=True)
            if r.returncode != 0:
                raise RuntimeError(f"venv creation failed:\n{r.stderr}")
            self._push("  .venv created.", "ok")
        return py

    def _step_build_tools(self) -> None:
        self._push("Upgrading pip / wheel / setuptools...", "info", 0.15)
        self._stream_pip([str(VENV_PIP), "install", "--upgrade",
                          "pip", "wheel", "setuptools",
                          "--no-cache-dir", "--quiet"])
        self._push("  Build tools up to date.", "ok")

    def _step_requirements(self) -> None:
        self._push("Installing Python dependencies...", "info", 0.20)
        self._push("  (this takes 3-10 minutes on first run)", "info")
        req = ROOT / "requirements.txt"
        self._stream_pip([str(VENV_PIP), "install", "-r", str(req),
                          "--prefer-binary", "--no-cache-dir"],
                         end_pct=0.75)
        self._push("  Dependencies installed.", "ok", 0.75)

    def _step_playwright(self) -> None:
        self._push("Installing Playwright browser...", "info", 0.77)
        try:
            r = subprocess.run(
                [str(VENV_PY), "-m", "playwright", "install", "chromium"],
                capture_output=True, text=True, timeout=120)
            if r.returncode == 0:
                self._push("  Playwright Chromium ready.", "ok")
            else:
                self._push("  Playwright install skipped (non-fatal).", "info")
        except Exception:
            self._push("  Playwright not installed (non-fatal).", "info")

    def _step_wakeword_models(self) -> None:
        self._push("Pre-downloading OpenWakeWord base models...", "info", 0.80)
        try:
            r = subprocess.run(
                [str(VENV_PY), "-c",
                 "import openwakeword; openwakeword.utils.download_models()"],
                capture_output=True, text=True, timeout=120)
            if r.returncode == 0:
                self._push("  Wake word models ready.", "ok")
            else:
                self._push("  Wake word pre-download skipped (non-fatal).", "info")
        except Exception:
            self._push("  OpenWakeWord models skipped (non-fatal).", "info")

    def _step_env(self, dirs: dict[str, str]) -> None:
        self._push("Writing .env configuration...", "info", 0.84)
        _write_env(
            chaotic=dirs["chaotic"],
            exotic=dirs["exotic"],
            piper_bin=dirs["piper_bin"],
            piper_voice=dirs["piper_voice"],
            wakeword=dirs["wakeword"],
        )
        self._push("  .env written.", "ok")

    def _step_shortcut(self) -> None:
        self._push("Creating desktop shortcut...", "info", 0.87)
        _create_shortcut(ROOT)
        self._push("  Albedo shortcut created on Desktop.", "ok")

    def _step_ollama(self) -> None:
        self._push("Pulling Ollama model (llama3.2:3b)...", "info", 0.90)
        self._push("  This may take 5-15 minutes. Do not close this window.", "info")
        try:
            proc = subprocess.Popen(
                ["ollama", "pull", "llama3.2:3b"],
                stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
            for line in proc.stdout:
                self._push(f"  {line.rstrip()}", "info")
            proc.wait()
            if proc.returncode == 0:
                self._push("  Ollama model ready.", "ok", 0.98)
            else:
                self._push("  Ollama pull returned non-zero (may already be cached).",
                           "info", 0.98)
        except FileNotFoundError:
            self._push("  Ollama not on PATH. Run 'ollama pull llama3.2:3b' after install.",
                       "info", 0.98)

    def _stream_pip(self, cmd: list[str], end_pct: float | None = None) -> None:
        """Run a pip command and stream its output to the log."""
        try:
            proc = subprocess.Popen(
                cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
            for line in proc.stdout:
                stripped = line.strip()
                if stripped:
                    self._push(f"  {stripped}", "info")
            proc.wait()
            if proc.returncode not in (0,):
                self._push(f"  pip exited with code {proc.returncode}", "err")
        except Exception as exc:
            self._push(f"  pip error: {exc}", "err")
        if end_pct is not None:
            self._push("", "info", end_pct)


class CompletePage(Page):
    def __init__(self, parent, wizard: "SetupWizard"):
        super().__init__(parent, wizard)
        self._success_frame: ctk.CTkFrame | None = None
        self._fail_frame: ctk.CTkFrame | None = None
        self._build()

    def _build(self) -> None:
        self._success_frame = ctk.CTkFrame(self, fg_color="transparent")
        _label(self._success_frame, "INSTALLATION COMPLETE", size=16,
               bold=True, color=C_GREEN).pack(pady=(40, 12))
        _label(self._success_frame,
               "Albedo Mission Control is ready.\n"
               "Double-click the Albedo shortcut on your Desktop to launch.",
               color=C_TEXT).pack(pady=8)
        ctk.CTkButton(self._success_frame, text="LAUNCH ALBEDO NOW",
                      width=220, font=("Courier New", 13, "bold"),
                      fg_color=C_GREEN, hover_color="#009944",
                      text_color="#000000",
                      command=self._launch).pack(pady=16)
        ctk.CTkButton(self._success_frame, text="Exit", width=100,
                      font=("Courier New", 11), fg_color=C_BORDER,
                      command=self.wizard.destroy).pack()

        self._fail_frame = ctk.CTkFrame(self, fg_color="transparent")
        _label(self._fail_frame, "INSTALLATION FAILED", size=16,
               bold=True, color=C_DANGER).pack(pady=(40, 12))
        _label(self._fail_frame,
               "Review the log on the previous page for details.\n"
               "Common fixes: run as Administrator, ensure winget is available.",
               color=C_TEXT).pack(pady=8)
        ctk.CTkButton(self._fail_frame, text="Back", width=100,
                      font=("Courier New", 11), fg_color=C_BORDER,
                      command=lambda: self.wizard.go_page(2)).pack(pady=12)
        ctk.CTkButton(self._fail_frame, text="Exit", width=100,
                      font=("Courier New", 11), fg_color=C_BORDER,
                      command=self.wizard.destroy).pack()

    def show(self, success: bool) -> None:
        if success:
            self._fail_frame.pack_forget()
            self._success_frame.pack(fill="both", expand=True)
        else:
            self._success_frame.pack_forget()
            self._fail_frame.pack(fill="both", expand=True)

    def _launch(self) -> None:
        try:
            subprocess.Popen(
                ["powershell.exe", "-ExecutionPolicy", "Bypass",
                 "-WindowStyle", "Normal", "-File",
                 str(ROOT / "Launch-Albedo.ps1")])
        except Exception:
            pass
        self.wizard.destroy()


# ── Wizard shell ───────────────────────────────────────────────────────────

class SetupWizard(ctk.CTk):
    def __init__(self) -> None:
        super().__init__()
        self.title("ALBEDO  //  SETUP WIZARD")
        self.geometry("680x620")
        self.resizable(False, False)
        self.configure(fg_color=C_BG)

        self._page_idx = 0
        self._build_ui()

    def _build_ui(self) -> None:
        # Header
        hdr = ctk.CTkFrame(self, fg_color=C_PANEL, corner_radius=0, height=58)
        hdr.pack(fill="x")
        hdr.pack_propagate(False)
        _label(hdr, "ALBEDO  //  SETUP WIZARD", size=17, bold=True,
               color=C_CYAN).pack(side="left", padx=20, pady=12)
        self._step_lbl = _label(hdr, "1 / 4", color=C_MUTED, size=11)
        self._step_lbl.pack(side="right", padx=20)

        # Content area
        self._content = ctk.CTkFrame(self, fg_color=C_BG, corner_radius=0)
        self._content.pack(fill="both", expand=True)

        # Build pages
        self.check_page    = SystemCheckPage(self._content, self)
        self.dir_page      = DirectoryPage(self._content, self)
        self.install_page  = InstallPage(self._content, self)
        self.complete_page = CompletePage(self._content, self)
        self._pages = [self.check_page, self.dir_page,
                       self.install_page, self.complete_page]

        # Nav bar
        nav = ctk.CTkFrame(self, fg_color=C_PANEL, corner_radius=0, height=54)
        nav.pack(fill="x", side="bottom")
        nav.pack_propagate(False)

        self._cancel_btn = ctk.CTkButton(nav, text="Cancel", width=90,
                                         font=("Courier New", 11),
                                         fg_color=C_BORDER, hover_color=C_DANGER,
                                         command=self.destroy)
        self._cancel_btn.pack(side="left", padx=12, pady=10)

        self._back_btn = ctk.CTkButton(nav, text="< Back", width=90,
                                       font=("Courier New", 11),
                                       fg_color=C_BORDER, hover_color=C_DIM,
                                       command=self._back)
        self._back_btn.pack(side="left", padx=4, pady=10)

        self._next_btn = ctk.CTkButton(nav, text="Next >", width=120,
                                       font=("Courier New", 12, "bold"),
                                       command=self._next)
        self._next_btn.pack(side="right", padx=12, pady=10)

        self._show_page(0)

    def _show_page(self, idx: int) -> None:
        for p in self._pages:
            p.pack_forget()
        self._page_idx = idx
        page = self._pages[idx]
        page.pack(fill="both", expand=True)
        page.on_enter()
        self._step_lbl.configure(text=f"{idx + 1} / 4")
        self._back_btn.configure(state="normal" if idx > 0 else "disabled")
        if idx == 2:
            self._next_btn.configure(text="Installing...", state="disabled")
        elif idx == 3:
            self._next_btn.configure(state="disabled")
            self._cancel_btn.configure(state="disabled")
        else:
            self._next_btn.configure(text="Next >")

    def set_next_enabled(self, enabled: bool) -> None:
        self._next_btn.configure(state="normal" if enabled else "disabled")

    def _next(self) -> None:
        if self._page_idx < len(self._pages) - 1:
            self._show_page(self._page_idx + 1)

    def _back(self) -> None:
        if self._page_idx > 0:
            self._show_page(self._page_idx - 1)

    def go_page(self, idx: int) -> None:
        self._show_page(idx)

    def go_to_complete(self, success: bool) -> None:
        self._show_page(3)
        self.complete_page.show(success)


# ── Entry point ────────────────────────────────────────────────────────────

if __name__ == "__main__":
    app = SetupWizard()
    app.mainloop()
