"""
Albedo Mobile Relay Server
==========================

Tiny WebSocket relay that lets the Albedo phone app reach the Albedo
desktop through a home router without port forwarding.

Architecture
------------
  Albedo PC  ──WS──►  /ws/albedo/{token}  ──►  relay  ──►  /ws/phone/{token}  ──WS──  Phone app
                                              (this server)

Both sides connect with the same token. The relay forwards every JSON
message from one side to the other. No message storage — if the other
side isn't connected the message is dropped (Albedo queues locally).

Endpoints
---------
  GET  /health                  — liveness probe for Fly.io
  POST /pair                    — register a new Albedo instance, returns token
  GET  /status/{token}          — is Albedo currently connected?
  WS   /ws/albedo/{token}       — Albedo persistent connection
  WS   /ws/phone/{token}        — Phone app connection (multiple allowed)

Token
-----
A 32-character hex string (128-bit random). Generated by Albedo Mission
Control and stored in settings.json. The phone gets it via QR scan or
manual entry. There is no user account — the token IS the identity.

Security
--------
  - All traffic over WSS / HTTPS (Fly.io provides TLS termination)
  - Token is cryptographically random — unguessable
  - Rate-limited: max 5 pair requests per IP per minute
  - Max 8 phone connections per token (prevents abuse)

Deploy
------
  cd relay/
  fly launch --name albedo-relay --region sea
  fly deploy
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import secrets
import time
from collections import defaultdict
from typing import Optional

from fastapi import FastAPI, WebSocket, WebSocketDisconnect, HTTPException, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("relay")

app = FastAPI(title="Albedo Relay", version="1.0.0", docs_url=None, redoc_url=None)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# In-memory connection registry
# {token: {"albedo": WebSocket | None, "phones": [WebSocket, ...]}}
# ---------------------------------------------------------------------------

_registry: dict[str, dict] = {}
_registry_lock = asyncio.Lock()

# Pair rate-limiting: {ip: [(timestamp, ...), ...]}
_pair_times: dict[str, list[float]] = defaultdict(list)

MAX_PHONES      = 8       # max simultaneous phone connections per token
PAIR_RATE_LIMIT = 5       # max pair calls per IP per minute
TOKEN_LENGTH    = 32      # hex chars (128-bit)


def _new_token() -> str:
    return secrets.token_hex(TOKEN_LENGTH // 2)


def _entry(token: str) -> dict:
    """Get or create a registry entry for this token."""
    if token not in _registry:
        _registry[token] = {"albedo": None, "phones": [], "created": time.time()}
    return _registry[token]


# ---------------------------------------------------------------------------
# HTTP endpoints
# ---------------------------------------------------------------------------

@app.get("/")
async def root():
    """Redirect root to the PWA."""
    from fastapi.responses import RedirectResponse
    return RedirectResponse(url="/app/")

# Serve the PWA at /app/
import os as _os
_static_dir = _os.path.join(_os.path.dirname(__file__), "static")
if _os.path.isdir(_static_dir):
    app.mount("/app", StaticFiles(directory=_static_dir, html=True), name="pwa")

@app.get("/health")
async def health():
    return {"ok": True, "connections": len(_registry)}


@app.post("/pair")
async def pair(request: Request):
    """
    Register a new Albedo instance.

    Albedo Mission Control calls this once on first setup to get a token.
    Subsequent startups reconnect via WS without calling /pair again.

    Body (optional JSON): {"token": "existing_token"}
    Returns: {"token": "...", "relay_url": "wss://..."}
    """
    # Rate-limit by IP
    ip = request.client.host if request.client else "unknown"
    now = time.time()
    times = _pair_times[ip]
    _pair_times[ip] = [t for t in times if now - t < 60]
    if len(_pair_times[ip]) >= PAIR_RATE_LIMIT:
        raise HTTPException(status_code=429, detail="Too many pair requests")
    _pair_times[ip].append(now)

    # Accept an existing token or generate a new one
    body: dict = {}
    try:
        body = await request.json()
    except Exception:
        pass
    token = body.get("token", "").strip() or _new_token()

    # Validate token format
    if len(token) != TOKEN_LENGTH or not all(c in "0123456789abcdef" for c in token):
        token = _new_token()

    async with _registry_lock:
        _entry(token)

    relay_host = os.environ.get("RELAY_HOST", request.base_url.hostname)
    relay_url  = f"wss://{relay_host}/ws"

    log.info(f"pair: token={token[:8]}... ip={ip}")
    return {"token": token, "relay_url": relay_url}


@app.get("/status/{token}")
async def status(token: str):
    """Is Albedo currently connected for this token?"""
    async with _registry_lock:
        entry = _registry.get(token)
    if entry is None:
        return {"ok": False, "albedo_connected": False, "phones": 0}
    return {
        "ok": True,
        "albedo_connected": entry["albedo"] is not None,
        "phones": len(entry["phones"]),
    }


# ---------------------------------------------------------------------------
# WebSocket relay
# ---------------------------------------------------------------------------

async def _send_json(ws: WebSocket, payload: dict) -> bool:
    """Send JSON to a WebSocket. Returns False on error."""
    try:
        await ws.send_text(json.dumps(payload))
        return True
    except Exception:
        return False


@app.websocket("/ws/albedo/{token}")
async def ws_albedo(ws: WebSocket, token: str):
    """Albedo desktop connects here. One connection per token."""
    await ws.accept()

    async with _registry_lock:
        entry = _entry(token)
        old = entry["albedo"]
        entry["albedo"] = ws

    log.info(f"albedo connected: token={token[:8]}...")

    # Close any stale previous connection
    if old is not None:
        try:
            await old.close(code=1001)
        except Exception:
            pass

    # Notify any waiting phones that Albedo is now online
    async with _registry_lock:
        phones = list(entry["phones"])
    for phone in phones:
        await _send_json(phone, {"type": "albedo_status", "online": True})

    try:
        while True:
            raw = await ws.receive_text()
            try:
                msg = json.loads(raw)
            except Exception:
                continue

            # Forward to all connected phones
            async with _registry_lock:
                phones = list(entry["phones"])

            dead = []
            for phone in phones:
                ok = await _send_json(phone, msg)
                if not ok:
                    dead.append(phone)

            if dead:
                async with _registry_lock:
                    entry["phones"] = [p for p in entry["phones"] if p not in dead]

    except WebSocketDisconnect:
        pass
    finally:
        async with _registry_lock:
            if entry.get("albedo") is ws:
                entry["albedo"] = None
        # Notify phones
        async with _registry_lock:
            phones = list(entry["phones"])
        for phone in phones:
            await _send_json(phone, {"type": "albedo_status", "online": False})
        log.info(f"albedo disconnected: token={token[:8]}...")


@app.websocket("/ws/phone/{token}")
async def ws_phone(ws: WebSocket, token: str):
    """Phone app connects here. Multiple phones per token allowed."""
    await ws.accept()

    async with _registry_lock:
        entry = _entry(token)
        if len(entry["phones"]) >= MAX_PHONES:
            await ws.close(code=1008, reason="too many connections")
            return
        entry["phones"].append(ws)
        albedo_online = entry["albedo"] is not None

    log.info(f"phone connected: token={token[:8]}... (total={len(entry['phones'])})")

    # Tell the phone whether Albedo is currently online
    await _send_json(ws, {"type": "albedo_status", "online": albedo_online})

    try:
        while True:
            raw = await ws.receive_text()
            try:
                msg = json.loads(raw)
            except Exception:
                continue

            # Forward to Albedo
            async with _registry_lock:
                albedo_ws = entry.get("albedo")

            if albedo_ws is not None:
                ok = await _send_json(albedo_ws, msg)
                if not ok:
                    async with _registry_lock:
                        if entry.get("albedo") is albedo_ws:
                            entry["albedo"] = None
            else:
                # Albedo offline — echo a queued response so the phone knows
                await _send_json(ws, {
                    "type": "error",
                    "id": msg.get("id"),
                    "text": "Albedo is offline. Make sure the desktop app is running.",
                })

    except WebSocketDisconnect:
        pass
    finally:
        async with _registry_lock:
            if ws in entry["phones"]:
                entry["phones"].remove(ws)
        log.info(f"phone disconnected: token={token[:8]}...")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=int(os.environ.get("PORT", 8080)))
