"""
brain_growth.py — Albedo Smart Brain: autonomous Obsidian vault intelligence.

The "Metakaihos" concept (from Greek: meta = beyond, kairos = opportune moment)
describes a system where knowledge doesn't just accumulate — it actively forms
connections and synthesises insights across domains when the moment is right.

Four growth mechanisms:

1. CONVERSATION MINING
   After each session, scans conversation logs for high-value knowledge.
   Extracts facts, decisions, and insights → writes atomic Obsidian notes.
   "You told me how to wire a DHT22 last Tuesday" — it's in the vault now.

2. AUTO-LINKING
   When a note is created or updated, queries ChromaDB for semantically
   related existing notes and injects [[wikilinks]] into both notes.
   Creates the graph organically — no manual tagging required.

3. CONCEPT SYNTHESIS
   During idle cycles, scans all vault notes for concept clusters that
   frequently appear together but have no dedicated synthesis note.
   Generates bridge notes: "3D Printing + ESP32 → Auto Print Monitoring"
   These are IDEAS generated by the system, surfaced to you for review.

4. VAULT RE-INDEXING
   Any note creation/modification immediately re-indexes changed notes
   in ChromaDB so future RAG queries find the new content.

Integration:
   Called from albedo/dream/orchestrator.py during idle cycles.
   Vault path from OBSIDIAN_VAULT_PATH in .env.

Architecture Note:
   Mining and synthesis use Gemini for extraction (cheap, fast, no VRAM).
   Similarity search uses ChromaDB (already running for RAG).
   All writes go directly to the Obsidian vault as .md files.
   Albedo gets smarter every time it's used — compound interest on knowledge.
"""

from __future__ import annotations

import json
import os
import re
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

# ── Config ─────────────────────────────────────────────────────────────────────

_VAULT_PATH = Path(os.getenv("OBSIDIAN_VAULT_PATH", ""))
_INBOX      = _VAULT_PATH / "_inbox"       # auto-generated notes land here
_SYNTHESIS  = _VAULT_PATH / "_synthesis"   # cross-domain synthesis notes
_META       = _VAULT_PATH / "_meta"        # MOCs (Maps of Content)

_GEMINI_KEY   = os.getenv("GEMINI_API_KEY", "")
_GEMINI_MODEL = os.getenv("GEMINI_MODEL",   "gemini-2.0-flash")

# How many characters minimum for a conversation turn to be worth mining
_MIN_RESPONSE_LENGTH = 120

# Max age (seconds) for a conversation log to be mined (24h)
_MAX_LOG_AGE_SECONDS = 86400

# How many related notes to find for auto-linking
_LINK_CANDIDATES = 5
_LINK_THRESHOLD  = 0.75   # cosine similarity threshold for auto-link

# Synthesis: minimum co-occurrence count before generating a bridge note
_SYNTHESIS_THRESHOLD = 3


# ── Gemini helper ──────────────────────────────────────────────────────────────

def _gemini(prompt: str, temperature: float = 0.3) -> str | None:
    """Call Gemini for content extraction and synthesis. Returns text or None."""
    if not _GEMINI_KEY:
        return None
    try:
        import google.generativeai as genai
        genai.configure(api_key=_GEMINI_KEY)
        m = genai.GenerativeModel(_GEMINI_MODEL)
        resp = m.generate_content(
            prompt,
            generation_config={"temperature": temperature, "max_output_tokens": 1024},
        )
        return resp.text.strip() if resp.text else None
    except Exception as exc:
        print(f"[brain_growth] Gemini error: {exc}")
        return None


# ── ChromaDB helpers ───────────────────────────────────────────────────────────

def _get_chroma_collection():
    """Get the primary ChromaDB collection used for vault RAG."""
    try:
        import chromadb
        client = chromadb.PersistentClient(
            path=str(Path(__file__).resolve().parent.parent.parent / "chroma_db")
        )
        return client.get_or_create_collection("obsidian_vault")
    except Exception as exc:
        print(f"[brain_growth] ChromaDB error: {exc}")
        return None


def _embed_and_index(note_path: Path, content: str) -> bool:
    """Add or update a note in ChromaDB for RAG."""
    collection = _get_chroma_collection()
    if not collection:
        return False
    try:
        doc_id = str(note_path.relative_to(_VAULT_PATH)).replace("\\", "/")
        collection.upsert(
            ids=[doc_id],
            documents=[content],
            metadatas=[{
                "source": "obsidian",
                "path":   doc_id,
                "title":  note_path.stem,
                "mtime":  str(note_path.stat().st_mtime),
            }],
        )
        return True
    except Exception as exc:
        print(f"[brain_growth] Index error for {note_path.name}: {exc}")
        return False


def _find_related(content: str, n: int = _LINK_CANDIDATES) -> list[dict]:
    """Find semantically related notes in the vault via ChromaDB."""
    collection = _get_chroma_collection()
    if not collection:
        return []
    try:
        results = collection.query(
            query_texts=[content[:1000]],
            n_results=min(n, collection.count()),
            include=["documents", "metadatas", "distances"],
        )
        candidates = []
        for meta, dist in zip(
            results["metadatas"][0], results["distances"][0]
        ):
            similarity = 1 - dist   # chroma returns L2 distance; approximate
            if similarity >= _LINK_THRESHOLD:
                candidates.append({"title": meta["title"], "path": meta["path"],
                                   "similarity": similarity})
        return candidates
    except Exception as exc:
        print(f"[brain_growth] Similarity search error: {exc}")
        return []


# ── Note writing ───────────────────────────────────────────────────────────────

def _write_note(folder: Path, title: str, content: str,
                tags: list[str] | None = None) -> Path | None:
    """Write an Obsidian markdown note. Returns path or None on failure."""
    if not _VAULT_PATH.exists():
        print(f"[brain_growth] Vault not found: {_VAULT_PATH}")
        return None

    folder.mkdir(parents=True, exist_ok=True)

    # Sanitize title for filename
    safe_title = re.sub(r'[<>:"/\\|?*]', "", title).strip()[:80]
    if not safe_title:
        return None

    note_path = folder / f"{safe_title}.md"

    # Build frontmatter
    tag_list  = "\n".join(f"  - {t}" for t in (tags or ["albedo-generated"]))
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")
    frontmatter = (
        f"---\n"
        f"title: {safe_title}\n"
        f"created: {timestamp}\n"
        f"source: albedo-brain\n"
        f"tags:\n{tag_list}\n"
        f"---\n\n"
    )

    # Append if exists, create if not
    if note_path.exists():
        existing = note_path.read_text(encoding="utf-8")
        # Don't duplicate if content is very similar
        if content[:100] in existing:
            return note_path
        note_path.write_text(existing + f"\n\n---\n*Updated: {timestamp}*\n\n" + content,
                             encoding="utf-8")
    else:
        note_path.write_text(frontmatter + content, encoding="utf-8")

    return note_path


def _inject_links(note_path: Path, related: list[dict]) -> None:
    """Append a 'Related' section with wikilinks to a note."""
    if not related or not note_path.exists():
        return
    existing = note_path.read_text(encoding="utf-8")
    if "## Related" in existing:
        return   # already has links
    link_lines = "\n".join(f"- [[{r['title']}]]" for r in related)
    note_path.write_text(
        existing + f"\n\n## Related\n{link_lines}\n",
        encoding="utf-8"
    )


# ── Mechanism 1: Conversation Mining ──────────────────────────────────────────

def mine_conversation_logs() -> int:
    """
    Scan conversation logs for learnable content and write atomic notes.
    Returns number of notes created.
    """
    log_dir = Path(__file__).resolve().parent.parent.parent / "logs"
    if not log_dir.exists():
        return 0

    notes_created = 0
    cutoff = time.time() - _MAX_LOG_AGE_SECONDS

    for log_file in sorted(log_dir.glob("*.jsonl"))[-5:]:   # last 5 session logs
        if log_file.stat().st_mtime < cutoff:
            continue

        try:
            turns = []
            with open(log_file, encoding="utf-8") as f:
                for line in f:
                    try:
                        turns.append(json.loads(line))
                    except Exception:
                        pass
        except Exception:
            continue

        # Extract Q+A pairs worth preserving
        for i, turn in enumerate(turns):
            if turn.get("role") != "assistant":
                continue
            response = turn.get("content", "")
            if len(response) < _MIN_RESPONSE_LENGTH:
                continue

            # Get preceding user message
            user_msg = ""
            if i > 0 and turns[i-1].get("role") == "user":
                user_msg = turns[i-1].get("content", "")

            if not user_msg:
                continue

            # Ask Gemini if this exchange is worth preserving as a note
            decision_prompt = (
                f"Given this Q&A exchange, decide if it contains factual knowledge, "
                f"a technical explanation, a decision, or a process that's worth "
                f"preserving in a personal knowledge base.\n\n"
                f"Q: {user_msg[:300]}\nA: {response[:500]}\n\n"
                f"If YES, respond with:\n"
                f"TITLE: <concise note title>\n"
                f"TAGS: <comma-separated tags, 2-4 words each>\n"
                f"SUMMARY: <1-3 sentence summary of the key knowledge>\n\n"
                f"If NO (it's chitchat, greeting, or trivial), respond with just: NO"
            )

            result = _gemini(decision_prompt)
            if not result or result.strip().upper().startswith("NO"):
                continue

            # Parse the response
            title_m   = re.search(r"TITLE:\s*(.+)", result)
            tags_m    = re.search(r"TAGS:\s*(.+)",  result)
            summary_m = re.search(r"SUMMARY:\s*(.+)", result, re.DOTALL)

            if not (title_m and summary_m):
                continue

            title   = title_m.group(1).strip()
            summary = summary_m.group(1).strip()
            tags    = [t.strip() for t in tags_m.group(1).split(",")] if tags_m else []

            content = (
                f"{summary}\n\n"
                f"**Original question:** {user_msg[:200]}\n\n"
                f"**Full answer excerpt:** {response[:600]}"
            )

            note_path = _write_note(_INBOX, title, content, tags=tags + ["mined"])
            if note_path:
                # Index in ChromaDB immediately
                _embed_and_index(note_path, content)

                # Find related notes and inject links
                related = _find_related(content)
                if related:
                    _inject_links(note_path, related)
                    # Back-link: inject link to new note in the most similar existing note
                    for rel in related[:2]:
                        rel_path = _VAULT_PATH / rel["path"]
                        if rel_path.exists():
                            existing = rel_path.read_text(encoding="utf-8")
                            if f"[[{title}]]" not in existing:
                                rel_path.write_text(
                                    existing + f"\n- [[{title}]]\n",
                                    encoding="utf-8"
                                )

                notes_created += 1
                print(f"[brain_growth] Mined note: '{title}'")

    return notes_created


# ── Mechanism 2: Auto-linking (post-write) ────────────────────────────────────

def autolink_new_notes(max_notes: int = 20) -> int:
    """
    Find recently created notes in _inbox that don't have a Related section.
    Query ChromaDB for related notes and inject links into both sides.
    Returns number of notes linked.
    """
    if not _INBOX.exists():
        return 0

    linked = 0
    cutoff = time.time() - (7 * 86400)   # notes from last 7 days

    for note_path in _INBOX.glob("*.md"):
        if note_path.stat().st_mtime < cutoff:
            continue
        content = note_path.read_text(encoding="utf-8")
        if "## Related" in content:
            continue
        if linked >= max_notes:
            break

        related = _find_related(content)
        if related:
            _inject_links(note_path, related)
            linked += 1
            print(f"[brain_growth] Auto-linked: '{note_path.stem}' → "
                  f"{[r['title'] for r in related]}")

    return linked


# ── Mechanism 3: Concept Synthesis ────────────────────────────────────────────

def synthesise_concepts(max_notes: int = 3) -> int:
    """
    Scan vault for concept clusters and generate synthesis bridge notes.
    Returns number of synthesis notes created.
    """
    if not _VAULT_PATH.exists():
        return 0

    # Collect all existing note titles
    all_titles = [p.stem for p in _VAULT_PATH.rglob("*.md")
                  if not p.stem.startswith(".")]
    if len(all_titles) < 10:
        return 0   # Not enough material yet

    # Ask Gemini to identify synthesis opportunities
    titles_sample = "\n".join(all_titles[:100])
    synthesis_prompt = (
        f"You are analysing a personal knowledge base (Obsidian vault). "
        f"Here are the note titles:\n\n{titles_sample}\n\n"
        f"Identify up to {max_notes} pairs or clusters of topics that appear in the "
        f"vault and would benefit from a SYNTHESIS note — a bridge note that connects "
        f"them and explores their relationship.\n\n"
        f"Format your response as JSON:\n"
        f"[\n"
        f"  {{\n"
        f"    \"title\": \"Synthesis note title\",\n"
        f"    \"topics\": [\"topic1\", \"topic2\"],\n"
        f"    \"synthesis\": \"2-4 sentence synthesis of how these relate and what insights emerge\",\n"
        f"    \"tags\": [\"tag1\", \"tag2\"]\n"
        f"  }}\n"
        f"]\n\n"
        f"Only suggest syntheses that are genuinely insightful, not obvious. "
        f"Return only valid JSON array."
    )

    result = _gemini(synthesis_prompt, temperature=0.5)
    if not result:
        return 0

    # Extract JSON
    json_m = re.search(r"\[[\s\S]+\]", result)
    if not json_m:
        return 0

    try:
        suggestions = json.loads(json_m.group(0))
    except json.JSONDecodeError:
        return 0

    created = 0
    for suggestion in suggestions[:max_notes]:
        title    = suggestion.get("title", "")
        topics   = suggestion.get("topics", [])
        synthesis = suggestion.get("synthesis", "")
        tags     = suggestion.get("tags", [])

        if not (title and synthesis and topics):
            continue

        # Build the synthesis note content
        topic_links = " | ".join(f"[[{t}]]" for t in topics)
        content = (
            f"*Cross-domain synthesis generated by Albedo Brain Growth*\n\n"
            f"**Connected domains:** {topic_links}\n\n"
            f"## Synthesis\n\n{synthesis}\n\n"
            f"## Questions to explore\n\n"
            f"- How does understanding one domain improve the other?\n"
            f"- What patterns are shared?\n"
            f"- Where do they diverge?\n\n"
            f"*Review and expand this note manually.*"
        )

        note_path = _write_note(_SYNTHESIS, title, content,
                                tags=tags + ["synthesis", "albedo-generated"])
        if note_path:
            _embed_and_index(note_path, content)
            created += 1
            print(f"[brain_growth] Synthesis: '{title}'")

    return created


# ── Mechanism 4: Vault re-indexing ────────────────────────────────────────────

def reindex_vault(max_notes: int = 50, incremental: bool = True) -> int:
    """
    Index new or modified vault notes into ChromaDB.
    Incremental: only re-indexes notes newer than last full index.

    Returns number of notes indexed.
    """
    if not _VAULT_PATH.exists():
        return 0

    collection = _get_chroma_collection()
    if not collection:
        return 0

    # Load timestamp of last index run
    state_file = Path(__file__).parent / ".reindex_state.json"
    last_run   = 0.0
    if incremental and state_file.exists():
        try:
            last_run = json.loads(state_file.read_text())["last_run"]
        except Exception:
            pass

    indexed = 0
    for note_path in sorted(_VAULT_PATH.rglob("*.md"),
                            key=lambda p: p.stat().st_mtime, reverse=True):
        if indexed >= max_notes:
            break
        if incremental and note_path.stat().st_mtime <= last_run:
            break   # sorted by mtime desc, so all remaining are older
        if note_path.stem.startswith("."):
            continue

        try:
            content = note_path.read_text(encoding="utf-8")
            if _embed_and_index(note_path, content):
                indexed += 1
        except Exception as exc:
            print(f"[brain_growth] Reindex error {note_path.name}: {exc}")

    # Save last run timestamp
    state_file.write_text(json.dumps({"last_run": time.time()}))
    return indexed


# ── Mechanism 5: Surface forgotten knowledge ──────────────────────────────────

def surface_relevant(query: str) -> list[str]:
    """
    Given a query, find vault notes that are semantically related but
    haven't been accessed recently — surface 'forgotten' knowledge.

    Returns list of note titles to mention in the response.
    """
    related = _find_related(query, n=10)
    if not related:
        return []

    # Filter for notes that exist and have content
    surfaced = []
    for r in related:
        note_path = _VAULT_PATH / r["path"]
        if note_path.exists():
            surfaced.append(r["title"])

    return surfaced[:3]   # Surface at most 3 related notes


# ── MOC Generator ─────────────────────────────────────────────────────────────

def update_master_moc() -> None:
    """
    Update (or create) a Master Map of Content note listing all vault sections.
    This gives Obsidian's graph view a central hub and helps navigation.
    """
    if not _VAULT_PATH.exists():
        return

    _META.mkdir(parents=True, exist_ok=True)
    moc_path = _META / "Master MOC.md"

    # Group notes by top-level folder
    sections: dict[str, list[str]] = {}
    for note_path in sorted(_VAULT_PATH.rglob("*.md")):
        # Get top-level folder relative to vault
        parts = note_path.relative_to(_VAULT_PATH).parts
        if len(parts) == 1:
            folder = "Root"
        else:
            folder = parts[0]

        if folder.startswith("_"):
            continue   # Skip internal folders in MOC

        sections.setdefault(folder, []).append(note_path.stem)

    content_lines = [
        "# Master Map of Content\n",
        f"*Auto-generated by Albedo Brain Growth — {datetime.now().strftime('%Y-%m-%d')}*\n",
        "",
        "This note is the central hub of the vault. Click any link to navigate.\n",
    ]

    for folder, titles in sorted(sections.items()):
        content_lines.append(f"\n## {folder}\n")
        for title in titles[:30]:   # Cap at 30 per section
            content_lines.append(f"- [[{title}]]")
        if len(titles) > 30:
            content_lines.append(f"- *...and {len(titles)-30} more*")

    # Auto-generated sections
    if _INBOX.exists():
        inbox_notes = list(_INBOX.glob("*.md"))
        if inbox_notes:
            content_lines.append(f"\n## Albedo Inbox ({len(inbox_notes)} notes)\n")
            for p in sorted(inbox_notes, key=lambda x: x.stat().st_mtime, reverse=True)[:15]:
                content_lines.append(f"- [[{p.stem}]]")

    if _SYNTHESIS.exists():
        synth_notes = list(_SYNTHESIS.glob("*.md"))
        if synth_notes:
            content_lines.append(f"\n## Synthesis Notes ({len(synth_notes)} notes)\n")
            for p in sorted(synth_notes)[:10]:
                content_lines.append(f"- [[{p.stem}]]")

    moc_path.write_text("\n".join(content_lines), encoding="utf-8")
    print(f"[brain_growth] MOC updated: {len(sections)} sections")


# ── Public entry point ────────────────────────────────────────────────────────

def run_growth_cycle(depth: str = "light") -> dict:
    """
    Run a brain growth cycle. Called from the dream orchestrator during idle.

    depth:
        "light"  — reindex new notes + autolink (fast, ~30s)
        "medium" — light + conversation mining (~2 min, uses Gemini)
        "deep"   — medium + synthesis + MOC update (~5 min, uses Gemini)

    Returns summary dict with counts.
    """
    if not _VAULT_PATH.exists():
        print(f"[brain_growth] Vault not found at {_VAULT_PATH} — skipping.")
        return {}

    summary = {}
    print(f"[brain_growth] Starting {depth} growth cycle...")

    # Always: reindex new/modified notes
    indexed = reindex_vault(max_notes=30, incremental=True)
    summary["reindexed"] = indexed

    # Always: autolink new inbox notes
    linked = autolink_new_notes(max_notes=10)
    summary["autolinked"] = linked

    if depth in ("medium", "deep"):
        # Mine conversation logs for knowledge
        mined = mine_conversation_logs()
        summary["mined_notes"] = mined

    if depth == "deep":
        # Synthesise cross-domain concepts
        synthesised = synthesise_concepts(max_notes=2)
        summary["synthesised"] = synthesised

        # Update master MOC
        update_master_moc()
        summary["moc_updated"] = True

    print(f"[brain_growth] Cycle complete: {summary}")
    return summary
