"""
dream/cataloger.py — Full-system file catalog during dream cycle.

Walks configured directories (deeper than file_organizer — reads everywhere
the user has content), builds a ChromaDB index of every file's metadata, and
writes a structured catalog note to the Obsidian vault.

The ChromaDB index enables Albedo to answer "where is my project X?" or
"find all STL files I have" without a live disk scan.

Public API
----------
    build_catalog(interrupt=None, progress_cb=None) -> CatalogResult
"""
from __future__ import annotations

import hashlib
import os
import time
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Callable, Optional

# Directories to always exclude from cataloging
_EXCLUDE_DIRS = {
    "windows", "program files", "program files (x86)", "programdata",
    "system32", "syswow64", ".git", ".venv", "venv", "node_modules",
    "__pycache__", "$recycle.bin", "recovery", "boot", "efi",
    "system volume information",
}

# File extensions too large/binary/uninteresting to bother indexing
_EXCLUDE_EXT = {".tmp", ".bak", ".swp", ".lock", ".part"}


def _should_exclude(path: Path) -> bool:
    return any(p.lower() in _EXCLUDE_DIRS for p in path.parts)


@dataclass
class CatalogResult:
    total_files:   int           = 0
    total_size_mb: float         = 0.0
    by_category:   dict          = field(default_factory=dict)
    vault_note:    Optional[str] = None
    duration_s:    float         = 0.0
    indexed:       int           = 0


def _default_catalog_roots() -> list[Path]:
    home = Path.home()
    return [
        home / "Desktop",
        home / "Documents",
        home / "Downloads",
        home / "Pictures",
        home / "Videos",
        home / "Music",
        home / "3D Objects",
    ]


def _file_metadata(path: Path) -> dict:
    try:
        stat = path.stat()
        return {
            "path":      str(path),
            "name":      path.name,
            "ext":       path.suffix.lower(),
            "size_kb":   round(stat.st_size / 1024, 1),
            "modified":  datetime.fromtimestamp(stat.st_mtime).isoformat(timespec="seconds"),
            "parent":    str(path.parent),
        }
    except OSError:
        return {}


def _chroma_index(files: list[dict], interrupt: Optional[Callable]) -> int:
    """Upsert file metadata into ChromaDB collection 'file_catalog'."""
    indexed = 0
    try:
        import chromadb
        root    = Path(__file__).resolve().parent.parent.parent
        client  = chromadb.PersistentClient(path=str(root / "chroma_db"))
        col     = client.get_or_create_collection("file_catalog")

        batch_docs, batch_metas, batch_ids = [], [], []
        BATCH = 100

        for i, f in enumerate(files):
            if interrupt and interrupt():
                break
            if not f:
                continue
            doc_id = hashlib.md5(f["path"].encode()).hexdigest()
            doc    = f"{f['name']} — {f['ext']} — {f['parent']}"
            batch_docs.append(doc)
            batch_metas.append(f)
            batch_ids.append(doc_id)

            if len(batch_docs) >= BATCH:
                col.upsert(documents=batch_docs, metadatas=batch_metas, ids=batch_ids)
                indexed   += len(batch_docs)
                batch_docs, batch_metas, batch_ids = [], [], []

        if batch_docs:
            col.upsert(documents=batch_docs, metadatas=batch_metas, ids=batch_ids)
            indexed += len(batch_docs)
    except Exception as exc:
        print(f"[cataloger] ChromaDB indexing error: {exc}")
    return indexed


def _write_vault_note(result: CatalogResult) -> Optional[str]:
    """Append / overwrite a catalog summary note in the Obsidian vault."""
    vault_path = os.environ.get("OBSIDIAN_VAULT_PATH", "")
    if not vault_path:
        return None
    vault = Path(vault_path)
    if not vault.exists():
        return None

    now       = datetime.now()
    note_name = "Albedo System Catalog.md"
    note_path = vault / note_name

    lines = [
        f"# Albedo System Catalog",
        f"",
        f"> Last updated: {now.strftime('%Y-%m-%d %H:%M')} during dream cycle",
        f"",
        f"## Summary",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total files cataloged | {result.total_files:,} |",
        f"| Total size | {result.total_size_mb:,.1f} MB |",
        f"| ChromaDB entries | {result.indexed:,} |",
        f"| Scan duration | {result.duration_s:.1f}s |",
        f"",
        f"## Files by Category",
        f"",
    ]

    for cat, count in sorted(result.by_category.items(), key=lambda x: -x[1]):
        lines.append(f"- **{cat}**: {count:,} files")

    lines += [
        f"",
        f"---",
        f"*Auto-generated by Albedo dream cycle — do not edit manually.*",
    ]

    try:
        note_path.write_text("\n".join(lines), encoding="utf-8")
        return str(note_path)
    except OSError as exc:
        print(f"[cataloger] Could not write vault note: {exc}")
        return None


def build_catalog(
    catalog_roots: Optional[list[str]] = None,
    interrupt:     Optional[Callable[[], bool]] = None,
    progress_cb:   Optional[Callable[[str, float], None]] = None,
) -> CatalogResult:
    """
    Walk the user's file system, index all discovered files into ChromaDB,
    and write a summary note to the Obsidian vault.
    """
    def _prog(msg: str, frac: float) -> None:
        if progress_cb:
            progress_cb(msg, frac)
        print(f"[cataloger] {msg}")

    t0 = time.monotonic()

    roots = (
        [Path(r) for r in catalog_roots]
        if catalog_roots else
        _default_catalog_roots()
    )
    roots = [r for r in roots if r.exists()]

    _prog(f"Beginning catalog sweep across {len(roots)} root(s)…", 0.0)

    all_files: list[dict] = []
    by_category: dict[str, int] = {}

    from albedo.dream.file_organizer import _EXT_MAP  # reuse category map

    for ri, root in enumerate(roots):
        if interrupt and interrupt():
            break
        try:
            for path in root.rglob("*"):
                if interrupt and interrupt():
                    break
                if not path.is_file():
                    continue
                if _should_exclude(path):
                    continue
                if path.suffix.lower() in _EXCLUDE_EXT:
                    continue
                meta = _file_metadata(path)
                if not meta:
                    continue
                ext = meta["ext"]
                cat = _EXT_MAP.get(ext, "Misc")
                if cat == "_SKIP":
                    continue
                meta["category"] = cat
                all_files.append(meta)
                by_category[cat] = by_category.get(cat, 0) + 1
        except (PermissionError, OSError):
            pass

        _prog(f"Scanned {root.name} — {len(all_files):,} files so far",
              0.1 + 0.5 * (ri / len(roots)))

    total_size_mb = sum(f.get("size_kb", 0) for f in all_files) / 1024

    _prog(f"Indexing {len(all_files):,} files into ChromaDB…", 0.65)
    indexed = _chroma_index(all_files, interrupt)

    result = CatalogResult(
        total_files   = len(all_files),
        total_size_mb = round(total_size_mb, 1),
        by_category   = by_category,
        indexed       = indexed,
        duration_s    = round(time.monotonic() - t0, 1),
    )

    _prog("Writing vault catalog note…", 0.92)
    result.vault_note = _write_vault_note(result)

    _prog(f"Catalog complete — {result.total_files:,} files, "
          f"{result.indexed:,} indexed, {result.total_size_mb:,.0f} MB.", 1.0)
    return result
